/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package b;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void Test_registrar_usuario(){
        App classUnderTest = new App();
        boolean resultat = App.registrar_usuario("mart","mart@gmail.com", 3);
        assertTrue(resultat);
    }
    @Test 
    void Test_eliminar_usuario(){
        App classUnderTest = new App();
        boolean resultat = App.eliminar_usuario("mart","mart@gmail.com", 3);
        assertTrue(resultat);
    }
    


}
