/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package b;

import java.util.*;

import com.google.common.base.Strings;

public class App {
    List<Usuario> usuarios= new ArrayList<>();

    public List<Usuario> getUsuarios() {
        return usuarios;
    }
    public App() {
        this.usuarios =  new ArrayList<>();
    }

    public void registrar_usuario(String nombre, String correo, int id) {
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getId() == (id)) {
                return;
            }
        }

        Usuario usuarionuevo = new Usuario(nombre, correo, id);
        usuarios.add(usuarionuevo);
    }

    /*
     * public static boolean eliminar_usuario(String nombre,String correo, int id){
     * List<Usuario> usuarios = new ArrayList<>();
     * for (int i=0;i<usuarios.size();i++){
     * if(usuarios.get(i).getId()==(id)){
     * usuarios.remove(usuarios.get(i).getId());
     * return true;
     * }
     * }
     * return false;
     * }
     */
    

}