/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package b;

import java.util.*;

import com.google.common.base.Strings;

public class App {
    List<Usuario> usuarios= new ArrayList<>();
    List<Habitacion> habitaciones= new ArrayList<>();

    public App() {
        this.usuarios =  new ArrayList<>();
        this.habitaciones =  new ArrayList<>();
    }

    public List<Usuario> getUsuarios() {
        return usuarios;
    }
    

    public void registrar_usuario(String nombre, String correo, int id) {
        /* for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getId() == (id)) {
                return;
            }
        }
        */
        Usuario usuarionuevo = new Usuario(nombre, correo, id);
        usuarios.add(usuarionuevo);

    }
    
    public List<Habitacion> getHabitaciones() {
        return habitaciones;
    }
    

    public void añadir_habitacion(String tipus,int preu,int id) {
        /*for (int i = 0; i < habitaciones.size(); i++) {
            if (habitaciones.get(i).getId() == (id)) {
                return;
            }
        }
        */

        Habitacion nuevaHabitacion = new Habitacion(tipus,preu, id);
        habitaciones.add(nuevaHabitacion);

    }

    
    

}